language: ruby
cache: bundler
rvm:
- 2.1
before_script: bundle update
script: gem install html-proofer -- --use-system-libraries && bundle exec jekyll build -s site -d _site --trace && htmlproof ./_site
branches:
  only:
  - master
  - /post-(.*)/
