language:
  - ruby
  - node_js
rvm:
  - 2.2
node_js:
  - 6
cache:
  - bundler
install:
  - npm install
  - npm install -g gulp
before_script:
  - bundle update
script:
  - gulp
  - bundle exec jekyll build
  - bundle exec htmlproof ./_site
branches:
  only:
    - master
    - /post-(.*)/
