language:
  - ruby
rvm:
  - 2.2.3p0
cache:
  - bundler
install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  - npm install -g gulp
before_script:
  - bundle update
script:
  - gulp
  - bundle exec jekyll build
  - bundle exec htmlproof ./_site
branches:
  only:
    - master
    - /post-(.*)/
