# Site settings
title: azerty
header-img: images/back.png
email: fabio.an.oliveira@gmail.com
description: ""
baseurl: ""
url: "http://blog.foliveira.me"
twitter_username: fanoliveira
github_username:  foliveira

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less", "Gemfile", "LICENSE", "vendor", "README.md", ".travis.yml", ".gitignore"]
