# Site settings
title: "Ramblings"
header-img: images/banner.png
email: fabio.an.oliveira@gmail.com
description: "Fabio's blog'a thing"
baseurl: ""
url: "http://blog.foliveira.me"
twitter_username: fanoliveira
github_username:  foliveira

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less", "Gemfile", "LICENSE", "gulpfile.js", "README.md",
          ".travis.yml", ".gitignore", "package.json", "CNAME", ]
