# Site settings
title: "Blahg-a-tron"
header-img: images/banner.png
email: i@foliveira.me
description: "Because blog-a-tron was already taken"
baseurl: ""
url: "http://blog.foliveira.me"
twitter_username: fanoliveira
github_username:  foliveira

# Google stuff
verification_id: lriou8spi6F9DxkOPDwnWZUhUbKrxrqyUqUTeSapILE
analytics: UA-58916290-1

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less", "Gemfile", "LICENSE", "gulpfile.js", "README.md",
          ".travis.yml", ".gitignore", "package.json", "CNAME", "node_modules",
          "scripts", "styles", "vendor"]
